baseURL = "https://yucun430-jpg.github.io/wilna/"
title = "Wilna"
theme = "blist"
languageCode = "en-us"
canonifyURLs = true
relativeURLs = false

[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1
    languageName = "English"
    [languages.en.params]
      news = "News"

    [[languages.en.params.about]]
      content = "We are a research lab of Wilna, led by Prof. Lei Wang."

    [[languages.en.params.about]]
      content = "Our lab focuses on research."

    [[languages.en.params.about]]
      content = "Welcome to join us!"

    [[languages.en.menu.main]]
        name = "Research"
        url = "research"
        weight = 2
    [[languages.en.menu.main]]
        name = "People"
        url = "people"
        weight = 3
    [[languages.en.menu.main]]
        name = "Publications"
        url = "papers"
        weight = 4

  [languages.zh]
    contentDir = "content/zh"
    weight = 2
    languageName = "Chinese"
    [languages.zh.params]
      news = "新闻"

    [[languages.zh.params.about]]
      content = "我们是由王雷教授领导的Wilna研究实验室。"
    [[languages.zh.params.about]]
      content = "欢迎加入我们！"
    [[languages.zh.params.about]]
      content = "lei.wang@dlut.edu.cn"

    [[languages.zh.menu.main]]
        name = "研究课题"
        url = "research"
        weight = 2
    [[languages.zh.menu.main]]
        name = "团队介绍"
        url = "people"
        weight = 3
    [[languages.zh.menu.main]]
        name = "近期论文"
        url = "papers"
        weight = 4

[[params.introImages]]
  src = "intro/3.jpg"
[[params.introImages]]
  src = "intro/2.jpg"
[[params.introImages]]
  src = "intro/1.jpg"

[[params.logo]]
  light = "Dut.png"
  url = "https://www.dlut.edu.cn/"

[params]
  altLogo = "Dut.png"
  teamLogo = "logo1.png"
  defaultContentLanguage = "zh"
  defaultContentLanguageInSubdir = true
  enableEmoji = true
  enableRobotsTXT = true
  hasCJKLanguage = true
  ascentColor = "bg-blue-200"
  frontBundle = "news"
  hideMeta = false
  hideOtherLanguages = false
  toc = true
  tocOpen = true
  hidePageThumbnail = false
  joinus = true

[params.homepage.social]
  title = "Contact Us"
  description = "Feel free to contact us."

  [[params.homepage.social.icons]]
    website = "email"
    url = "lei.wang@dlut.edu.cn"
  [[params.homepage.social.icons]]
    website = "logo"
    src = "Dut.png"
    url = "https://www.dlut.edu.cn"

[build]
  writeStats = true
  future = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true